name: GDP
dimensions_title: by timescale
dimensions:
    - slug: timescale
      name: Time scale
      choices:
          - slug: maddison
            name: Long run GDP since 1 CE (Maddison)
            description: Estimated GDP for the last two millennia by the Maddison Database
          - slug: penn
            name: Modern GDP since 1950 (Penn)
            description: Modern GDP since after WWII by the Penn World Table project
          - slug: worldbank
            name: Modern GDP since 1990 (World Bank)
            description: Official GDP by the World Bank since 1990
    - slug: metric
      name: Metric
      choices:
          - slug: absolute
            name: Absolute values
          - slug: per_capita
            name: Per capita values
views:
    - dimensions:
          timescale: maddison
          metric: absolute
      indicator_path:
          900795: y
    - dimensions:
          timescale: maddison
          metric: per_capita
      indicator_path:
          900793: y
    - dimensions:
          timescale: penn
          metric: absolute
      indicator_path:
          539736: y
    - dimensions:
          timescale: penn
          metric: per_capita
      indicator_path:
          539760: y
    - dimensions:
          timescale: worldbank
          metric: absolute
      indicator_path:
          905482: y
    - dimensions:
          timescale: worldbank
          metric: per_capita
      indicator_path:
          905490: y