# %%
from os import path
from string import Template
import textwrap
import pandas as pd
import re
from collections import defaultdict


def file_url(tableSlug):
    return f"https://files.ourworldindata.org/data/unwpp-unstable-v3/{tableSlug}.csv?nocache"


# %%
def substitute_rows(row):
    # Rows can include placeholders like ${sex__slug}, which will be replaced here
    for key in row.keys():
        if isinstance(row[key], str):
            while "${" in row[key]:
                template = Template(row[key])
                row[key] = template.substitute(**row)
    return row


def table_def(tableSlugs, rows):
    table_slugs = "\t".join(tableSlugs)
    table_defs = [
        f"table	{file_url(tableSlug)}	{tableSlug}" for tableSlug in tableSlugs
    ]
    table_defs = "\n".join(table_defs)
    col_defs = [
        f"{row['ySlugs']}\t{row['title']}\tNumeric\t{row['metric__shortUnit']}\t{row['metric__unit']}"
        for (_, row) in rows.iterrows()
    ]
    col_defs = textwrap.indent("\n".join(col_defs), "\t")

    return f"""{table_defs}
columns	{table_slugs}
	slug	name	type	shortUnit	unit
	location	Country name	EntityName
	year	Year	Year
{col_defs}"""


# %%
outfile = "../../explorers/demography.explorer.tsv"

# %%
# Read inputs
with open("demography-explorer.template.tsv", "r") as templateFile:
    template = Template(templateFile.read())
input_files = ["metrics", "sex", "age_group", "projection"]
input_df = {
    file: pd.read_csv(f"{file}.csv", dtype=str, keep_default_na=False)
    for file in input_files
}
df = input_df["metrics"]

# %%
for merge_col in input_files[1:]:
    explode_col = "_" + merge_col
    df[explode_col] = df[explode_col].apply(lambda x: x.split(" "))
    df = df.explode(explode_col)
    merge_df = input_df[merge_col]
    merge_df.columns = merge_col + "__" + merge_df.columns.values
    df = df.merge(
        merge_df,
        how="left",
        left_on=explode_col,
        right_on=merge_col + "__slug",
        validate="many_to_one",
        indicator=merge_col + "__merge",
    )
    assert df[merge_col + "__merge"].isin(["both"]).all()
    df = df.drop([explode_col, merge_col + "__merge"], axis=1)

# %%

df = df.apply(substitute_rows, axis=1)
for col in ["title", "subtitle"]:
    df[col] = (
        df[col]
        .apply(lambda x: x.strip())
        .apply(lambda x: x[0].upper() + x[1:] if len(x) else x)
        .apply(lambda x: re.sub(" {2,}", " ", x))
    )

# %%
tables = df["tableSlug"].unique()
# below is a very complicated way to bundle together column definitions for multiple tables with common column names; might not be worthwhile
# we create a dict: table_slug -> column_names; then invert that to: column_names -> table_slugs
column_slugs_by_table = {
    tableSlug: df[df["tableSlug"] == tableSlug]["ySlugs"] for tableSlug in tables
}
tables_by_column_slugs = defaultdict(list)
rows = {}
for tableSlug, column_slugs in column_slugs_by_table.items():
    if tableSlug != "":
        tables_by_column_slugs[tuple(column_slugs)].append(tableSlug)
        rows[tuple(column_slugs)] = df[df["tableSlug"] == tableSlug]

table_defs = [
    table_def(tableSlugs, rows[column_slugs])
    for column_slugs, tableSlugs in tables_by_column_slugs.items()
]

# %%

col_rename = {
    "sex__name": "Sex Radio",
    "age_group__name": "Age group Dropdown",
    "projection__name": "Projection Scenario Radio",
}
df = df.rename(columns=col_rename)

# Reorder columns such that thed different Dropdown/Radio columns are next to each other
metric_dropdown_idx = df.columns.get_loc("Metric Dropdown")
cols = df.columns.tolist()
for i, col in enumerate(col_rename.values()):
    cols.remove(col)
    cols.insert(metric_dropdown_idx + 1 + i, col)
df = df.loc[:, cols]

# Drop all remaining programmatic columns containing __
df = df.drop(columns=df.filter(regex="__"))

# %%
graphers_tsv = df.to_csv(sep="\t", index=False)
graphers_tsv_indented = textwrap.indent(graphers_tsv, "\t")

table_defs = "\n".join(table_defs)

# %%
warning = "# DO NOT EDIT THIS FILE BY HAND. It is automatically generated using a set of input files. Any changes made directly to it will be overwritten.\n\n"

with open(outfile, "w", newline="\n") as f:
    f.write(
        warning
        + template.substitute(
            graphers_tsv=graphers_tsv_indented,
            table_defs=table_defs,
        )
    )

    print(f"💾 Explorer config written to {path.abspath(outfile)}")

# %%
