name: Population and demography explorer
on:
  push:
    branches:
      - master
      - staging
    paths:
      - "scripts/demography-explorer/**"
  pull_request:
    paths:
      - "scripts/demography-explorer/**"

# Auto-run the script generating the demography explorer spreadsheet, and push it as a commit to the respective branch

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      # - name: Install dependencies
      #   run: cd scripts/demography-explorer && poetry install

      # - name: Run population and demography explorer script
      #   run: cd scripts/demography-explorer && poetry run python demography-explorer.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 update demography-explorer"
