name: Global Food Explorer
on:
  push:
    branches:
      - master
      - staging
    paths:
      - "scripts/global-food-explorer/**"
  pull_request:
    paths:
      - "scripts/global-food-explorer/**"

# Auto-run the script generating the global food explorer spreadsheet, and push it as a commit to the respective branch

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: cd scripts/global-food-explorer && poetry install

      - name: Run global food explorer script
        run: cd scripts/global-food-explorer && poetry run python global-food-explorer.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 update global-food-explorer"
